# Generated by Django 5.1.4 on 2026-08-25 02:42

import django.db.models.deletion
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL标识')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': '新闻分类',
                'verbose_name_plural': '新闻分类',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='URL标识')),
                ('summary', models.CharField(blank=True, max_length=200, verbose_name='简述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_visible', models.BooleanField(default=True, verbose_name='显示')),
            ],
            options={
                'verbose_name': '产品分类',
                'verbose_name_plural': '产品分类',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='艾研信息', max_length=120, verbose_name='公司名称')),
                ('company_name_en', models.CharField(blank=True, default='AiYan Information', max_length=120, verbose_name='英文名称')),
                ('tagline', models.CharField(blank=True, default='为高校电子工程教育提供创新实验平台', max_length=200, verbose_name='品牌标语')),
                ('logo', models.ImageField(blank=True, upload_to='site/', verbose_name='Logo')),
                ('hero_title', models.CharField(default='让工程教育，回归动手实践', max_length=200, verbose_name='首页主标题')),
                ('hero_subtitle', models.TextField(default='从单片机到物联网，从电源拓扑到智能小车——为高校实验室打造的模块化教学套件。', verbose_name='首页副标题')),
                ('hero_image', models.ImageField(blank=True, help_text='可选，首页英雄区背景图。', upload_to='site/', verbose_name='首页主视觉')),
                ('about_title', models.CharField(blank=True, max_length=200, verbose_name='关于-标题')),
                ('about_body', models.TextField(blank=True, help_text='支持 HTML。', verbose_name='关于-正文')),
                ('contact_address', models.CharField(blank=True, max_length=200, verbose_name='地址')),
                ('contact_phone', models.CharField(blank=True, max_length=60, verbose_name='电话')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('contact_wechat', models.CharField(blank=True, max_length=100, verbose_name='微信公众号')),
                ('contact_icp', models.CharField(blank=True, max_length=100, verbose_name='备案号')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点设置',
                'verbose_name_plural': '站点设置',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='URL标识')),
                ('cover', models.ImageField(blank=True, upload_to=website.models.news_cover_upload_to, verbose_name='封面图')),
                ('excerpt', models.CharField(blank=True, max_length=300, verbose_name='摘要')),
                ('body', models.TextField(help_text='支持 HTML。', verbose_name='正文')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('is_published', models.BooleanField(default=True, verbose_name='发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='website.newscategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '新闻',
                'verbose_name_plural': '新闻',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='名称')),
                ('code', models.CharField(blank=True, help_text='产品型号，例如 AY-Smart Car', max_length=80, verbose_name='型号')),
                ('slug', models.SlugField(max_length=160, unique=True, verbose_name='URL标识')),
                ('tagline', models.CharField(blank=True, max_length=200, verbose_name='一句话卖点')),
                ('cover', models.ImageField(blank=True, help_text='列表与详情页主图，建议 1600x1200。', upload_to=website.models.product_cover_upload_to, verbose_name='封面图')),
                ('summary', models.TextField(blank=True, help_text='卡片上展示的简短描述。', verbose_name='简介')),
                ('description', models.TextField(blank=True, help_text='支持 HTML，详情页正文。', verbose_name='详细介绍')),
                ('specifications', models.TextField(blank=True, help_text='一行一项，用 | 分隔列。', verbose_name='规格参数')),
                ('featured', models.BooleanField(default=False, verbose_name='首页推荐')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_published', models.BooleanField(default=True, verbose_name='发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='website.productcategory', verbose_name='分类')),
            ],
            options={
                'verbose_name': '产品',
                'verbose_name_plural': '产品',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='文件标题')),
                ('file', models.FileField(help_text='支持 PDF、ZIP、BIN 等任意格式。', upload_to=website.models.product_doc_upload_to, verbose_name='文件')),
                ('size_hint', models.CharField(blank=True, help_text='可选，例如「3 MB」。', max_length=40, verbose_name='文件大小标注')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='website.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '产品资料',
                'verbose_name_plural': '产品资料',
                'ordering': ['order', '-published_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=website.models.product_gallery_upload_to, verbose_name='图片')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '产品图片',
                'verbose_name_plural': '产品图片',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='实验名称')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='顺序')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiments', to='website.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': '实验列表项',
                'verbose_name_plural': '实验列表项',
                'ordering': ['order', 'id'],
                'unique_together': {('product', 'order')},
            },
        ),
    ]
