# Generated by Django 5.1.4 on 2026-08-25 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('category', models.CharField(choices=[('doc', '文档类'), ('source', '代码类'), ('tool', '工具软件'), ('video', '视频资源')], default='doc', max_length=20, verbose_name='分类')),
                ('description', models.TextField(blank=True, help_text='可选，资源简述。', verbose_name='描述')),
                ('download_password', models.CharField(blank=True, help_text='原站下载密码提示，如 xxad。', max_length=40, verbose_name='下载密码')),
                ('file_size_hint', models.CharField(blank=True, help_text='可选，例如「2 MB」。', max_length=40, verbose_name='文件大小')),
                ('external_url', models.URLField(help_text='原 hpati.com 下载页 URL。', max_length=300, verbose_name='原站链接')),
                ('published_at', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_published', models.BooleanField(default=True, verbose_name='发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resources', to='website.product', verbose_name='关联产品')),
            ],
            options={
                'verbose_name': '资源',
                'verbose_name_plural': '资源',
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
    ]
