# Generated by Django 5.1.4 on 2026-08-26 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_fax',
            field=models.CharField(blank=True, max_length=60, verbose_name='传真'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='contact_zip',
            field=models.CharField(blank=True, max_length=20, verbose_name='邮编'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='map_lat',
            field=models.FloatField(blank=True, help_text='百度地图纬度,如 30.18991。', null=True, verbose_name='地图纬度'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='map_lng',
            field=models.FloatField(blank=True, help_text='百度地图经度,如 120.181077。', null=True, verbose_name='地图经度'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='work_hours',
            field=models.CharField(blank=True, help_text='例如「9:00-17:00」。', max_length=100, verbose_name='工作时间'),
        ),
    ]
