# Generated by Django 5.1.4 on 2026-08-26 07:23

import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sitesetting_contact_fax_sitesetting_contact_zip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, help_text='下载到本地的资源文件；留空则使用原站链接。', upload_to=website.models.resource_file_upload_to, verbose_name='本地文件'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='external_url',
            field=models.URLField(help_text='原 hpati.com 下载页 URL，本地无文件时回退使用。', max_length=300, verbose_name='原站链接'),
        ),
    ]
